Update usage.md
jrnl-org/jrnl pull request #1035
Opened 2020-08-24 15:52 UTC by jimmyhess

Move the `-and` option after two or more tags instead of in-between. Using this option in-between tags does not work if the jrnl file name is not `default`.

### Checklist

- [ ] I have read the [contributing doc](https://github.com/jrnl-org/jrnl/blob/develop/CONTRIBUTING.md).
- [ ] I have included a link to the relevant issue number.
- [ ] I have tested this code locally.
- [ ] I have checked to ensure there aren't other open [pull requests](../pulls)
  for the same issue.
- [ ] I have written new tests for these changes, as needed.
- [ ] All tests pass.

2020-08-26 17:54 UTC, jimmyhess reviewed
The quotation marks are necessary in Windows

2020-08-29 19:09 UTC, micahellison commented
> The quotation marks are necessary in Windows

Hi there, I'm testing this out on Windows 10 and it's working just fine without quotes. Can you clarify this?

2020-08-31 14:27 UTC, jimmyhess commented
From PowerShell, `jrnl @tag1 @tag2` launches the editor and `jrnl "@tag1" "@tag2"` prints the entries with `@tag1` *or* `@tag2`.

2020-09-10 00:53 UTC, wren requested changes
Thanks for submitting this, but the changes don't quite work for us. Please see below for specific notes on each of the changes.

For the two issues in this PR:

- `-and` can't be in between other arguments
  This was reported earlier (#853), and is fixed and merged. It's not released, yet (it's in v2.5), but we don't want to update the documentation for this since it's already fixed in the next version (which is when this documentation would be updated). Sorry for the confusion.

- Powershell requires escaping of `@` charcater
  We have a note in the docs on the [usage page](https://jrnl.sh/usage/) that tells users that most shells have reserved characters (like `#` and `*`, or in the case of powershell `@`). Maybe we could make that more prominent, or specifically call out powershell, but we don't want to add shell specific syntax into the general help (like putting quotes around each `-and` on the page).

2020-09-26 17:33 UTC, closed without merging