Use strict date matching, if using the default time format
jrnl-org/jrnl pull request #1045
Opened 2020-09-10 19:35 UTC by michaellenahan

### Description

- What is this new code intended to do?

After updating to v2, I noticed the bug described here: https://github.com/jrnl-org/jrnl/issues/625

jrnl version v2.4.5

Using this configuration:
```
(jrnl-hIZQiBQS-py3.8) ➜  jrnl git:(develop) cat ~/.config/jrnl/jrnl.yaml
colors:
  body: none
  date: none
  tags: none
  title: none
default_hour: 9
default_minute: 0
editor: 'atom'
encrypt: false
highlight: true
indent_character: '|'
journals:
  default: ~/notes/journal.txt
  home: ~/notes/home.txt
  test: ~/notes/test.txt
linewrap: 79
tagsymbols: '@'
template: false
timeformat: '%Y-%m-%d %H:%M'
version: v2.4.5
```

I'm doing my test on the "test" journal, which starts out like this:
```
[2020-09-10 19:47] Here is a chat log
[26/11, 23:32] Someone: chat line.
```

Before the patch: the second line is incorrectly parsed as a new entry.
```
(jrnl-hIZQiBQS-py3.8) ➜  jrnl git:(develop) ✗ jrnl test --short
2020-09-10 19:47 Here is a chat log
2020-09-10 23:32 Someone: chat line.
```

After the patch: as long as the default time format is unchanged, the second line is correctly interpreted as part of the first entry.
```
(jrnl-hIZQiBQS-py3.8) ➜  jrnl git:(develop) jrnl test --short
2020-09-10 19:47 Here is a chat log
```

- Are there any related issues?

https://github.com/jrnl-org/jrnl/issues/630
https://github.com/jrnl-org/jrnl/issues/625

- What is the motivation for this change?

I love to use jrnl as a notepad for when I am dealing with server downtime.
When I'm doing that, I often edit my jrnl directly and paste large amounts of server logs there.
Those log entries all start with an opening square bracket and usually have some sort of date.

My motivation:
I accept this is not a full solution to the problem, and it will only help those who do not change the default time format.
For people who do stick to the default, I think jrnl should try it's best to parse the date string at the beginning of an entry strictly.
That "fixes the bug" for the majority of users, and solves my problem.
Of course, if my log file entries have the same time format as jrnl, then jrnl will of course parse the log file entries too.
That's fine, because the default jrnl time format is '%Y-%m-%d %H:%M' and most log entries are accurate to the second or millisecond.

### Checklist

- [*] I have read the [contributing doc](https://github.com/jrnl-org/jrnl/blob/develop/CONTRIBUTING.md).
- [*] I have included a link to the relevant issue number.
- [*] I have tested this code locally.
- [*] I have checked to ensure there aren't other open [pull requests](../pulls)
  for the same issue.
- [ ] I have written new tests for these changes, as needed.
- [ ] All tests pass.
(I'm a new contributor, I'm not sure how to test, so I will submit the PR and see what happens)

2020-09-12 01:34 UTC, wren commented
Have to think about this one a bit. I'm not sure if this would break any current functionality for users depending on what timestamp they are using.

2020-09-13 16:54 UTC, michaellenahan commented
> Have to think about this one a bit. I'm not sure if this would break any current functionality for users depending on what timestamp they are using.

Another idea for this would be to offer a configuration setting in jrnl.yaml for an advanced user to provide a regex for strict matching.

That way you can be non-breaking for everyone, but have strict matching for those who know for certain that they want it.

2020-09-24 00:13 UTC, wren commented
Okay, thanks for you patience while I thought this all the way through. So, I think a config option (named `timeformat_strict` so it's alphabetized next to the format) is the best approach.

The problems I have with relying on the default format are the following:
- If a user hears about new strict matching and wants to use it, but they currently have a non-default time format. They'll naturally change their format back to the default. But with this PR, that config change wouldn't recognize any entries in their journal (since now strict mode is on and no entries have the default time format).
- If someone moves a journal between machines, they'll risk the same scenario above if the config doesn't match exactly.
- This leaves out users from countries that list the day first (`dd-mm-yyyy`).

If we do a config option instead (default should be false), then users should know what they're getting into when they turn it on.

2020-09-24 00:14 UTC, wren requested changes
Please do the config option instead as discussed in the comments.

2020-09-30 14:42 UTC, michaellenahan commented
Thanks! I've added the code for the timeformat_strict configuration option.
Tested locally with the following test.txt file:
```
[2020-09-10 19:47] Here is a chat log
[26/11, 23:32] Someone: chat line.
```
[1] Without any `timeformat_strict` entry in `~/.config/jrnl/jrnl.yaml`
```
(jrnl-hIZQiBQS-py3.8) ➜  jrnl git:(develop) jrnl test --short
2020-09-10 19:47 Here is a chat log
2020-09-30 23:32 Someone: chat line.
```
[2] After adding `timeformat_strict: true` to `~/.config/jrnl/jrnl.yaml`
```
(jrnl-hIZQiBQS-py3.8) ➜  jrnl git:(develop) jrnl test --short
2020-09-10 19:47 Here is a chat log
```
[3] After adding `timeformat_strict: false` to `~/.config/jrnl/jrnl.yaml`
```
(jrnl-hIZQiBQS-py3.8) ➜  jrnl git:(develop) jrnl test --short
2020-09-10 19:47 Here is a chat log
2020-09-30 23:32 Someone: chat line.
```

2020-09-30 14:51 UTC, michaellenahan commented
However, I have just found another bug:

Using this as the test.txt file (where I have defined "test" as one of my `jrnl`s, see configuration at the beginning of this discussion).
```
[2020-09-10 19:47] Here is a @chat log
the chat log is like this:
[26/11, 23:32] Someone: chat line.
```

This is incorrectly excluding the third line.
```
(jrnl-hIZQiBQS-py3.8) ➜  jrnl git:(develop) jrnl test @chat
2020-09-10 19:47 Here is a @chat log
| the chat log is like this:
```

If I "correct" the third line, by putting a `.` in front of the `[`, I get correct output:
```
(jrnl-hIZQiBQS-py3.8) ➜  jrnl git:(develop) jrnl test @chat
2020-09-10 19:47 Here is a @chat log
| the chat log is like this:
| .[26/11, 23:32] Someone: chat line.
```

2020-10-05 22:54 UTC, wren commented
Hi, @michaellenahan . I haven't time to properly review this yet (I'm in the middle of moving apartments). But can you please add the tests that you ran manually to one of the test files (in the`features`directory)? That would hi s long way to making sure this works as intended for everyone. I'll have time for a review and testing later this week. Thank you!

2020-10-10 19:24 UTC, wren commented
This doesn't quite work as requested. Someone would still need to have the default timestamp in order to be able to use strict parsing. This still has the same problems I outlined in my above comment.

I'm guessing your hesitation is coming from using a regex to parse the date (there's no way to make a regex to parse arbitrary date strings generated by a user). I think using [`strptime`](https://docs.python.org/3/library/datetime.html#datetime.datetime.strptime) in `time.py` instead of a regex in `Journal.py` would be a better implementation for this functionality.

What do you think?

2020-10-24 18:13 UTC, wren commented
Hi, I'm closing this for now to clean up the queue, but please feel free to reopen with the requested changes. Thanks, again!

2020-10-24 18:13 UTC, closed without merging

2020-10-31 18:13 UTC, michaellenahan commented
Hi,

I'm using a (clumsy but workable) workaround right now, whereby I put a period "." in front of those dates in square brackets, that I don't want to have interpreted as jrnl entries.

Thanks for taking the time to respond @wren !

Have not had time to look into your suggested solution and right now I don't know when I will be able to. I will leave this here for now, it can be re-opened if anyone else comes across it and is experiencing the same problem.