# 1170 alternate config file CLI argument
jrnl-org/jrnl pull request #1290
Opened 2021-07-06 16:39 UTC by samuelgregorovic

2021-07-08 06:53 UTC, wren commented
Thank you for submitting this! We'll take a look at it on Saturday this week.

2021-07-10 18:32 UTC, micahellison requested changes
This looks great. Thanks for submitting this, and for adding in documentation along with the improvement.

Would you be willing to add a couple BDD tests to ensure support for multiple journals? I see that it's currently working, but would like to be sure that it stays working as people modify this in the future. Basically, it would confirm that jrnl can read and write to a non-default journal while using the alternative config file argument:
```
jrnl secondjournal --cf test_config.yaml new journal entry
jrnl secondjournal --cf test_config.yaml -1
```

2021-07-10 18:39 UTC, wren commented on docs/advanced.md
> +You can specify an alternate configuration file fot the current instance of `jrnl` using `--config-file CONFIG_FILE_PATH` where
```suggestion
You can specify an alternate configuration file for the current instance of `jrnl` using `--config-file CONFIG_FILE_PATH` where
```

2021-07-10 18:46 UTC, samuelgregorovic commented
> This looks great. Thanks for submitting this, and for adding in documentation along with the improvement.
> 
> Would you be willing to add a couple BDD tests to ensure support for multiple journals? I see that it's currently working, but would like to be sure that it stays working as people modify this in the future. Basically, it would confirm that jrnl can read and write to a non-default journal while using the alternative config file argument:
> ```
> jrnl secondjournal --cf test_config.yaml new journal entry
> jrnl secondjournal --cf test_config.yaml -1
> ```

i dont really have experience with BDD but i can try to do it, if you won't suggest otherwisw

2021-07-10 18:55 UTC, micahellison commented
> i dont really have experience with BDD but i can try to do it

Feel free to take a look at `\tests\bdd\features\multiple_journals.feature` on the develop branch. You should be able to use roughly the same syntax as the tests in there to add in this use case.

2021-07-10 18:56 UTC, wren commented
@samuelgregorovic If you're up for it, please give it a shot! And if it doesn't work out or you need any help, just let us know and we can jump in.

2021-07-10 19:17 UTC, samuelgregorovic commented
> @samuelgregorovic If you're up for it, please give it a shot! And if it doesn't work out or you need any help, just let us know and we can jump in.

deal!

2021-07-10 19:17 UTC, samuelgregorovic commented
> > i dont really have experience with BDD but i can try to do it
> 
> Feel free to take a look at `\tests\bdd\features\multiple_journals.feature` on the develop branch. You should be able to use roughly the same syntax as the tests in there to add in this use case.

thanks for the heads up!

2021-07-11 09:40 UTC, samuelgregorovic commented
@wren @micahellison latest commit contains the BDD tests as you wanted. could you please look at them if they satisfy your expectations? thanks

2021-07-13 19:17 UTC, wren commented
@samuelgregorovic This is looking great. I think we didn't quite clarify one important point, though.

We currently have two BDD frameworks in place:
1. **Behave** (in `/features` folder)
  We're currently phasing out Behave, so we don't want to update or fix anything in the `/features` folder anymore.

2. **Pytest BDD** (in `/tests/bdd` folder)
  We recently moved over all of the tests from Behave into this in order to centralize all of our tests into Pytest (which we use for unit tests). Pytest BDD will be our BDD testing framework for the forseeable future.

Sorry for the misunderstanding! The work you've done here looks great, though. It seems like you took a current feature file, copied it over, and changed the tests to work for your tests. If you do the same thing, but start with the file mentioned above (`/tests/bdd/features/multiple_journals.feature`), then I think you'll be good to go.

The only bit of feedback I have is try to use existing config files if at all possible, rather than adding any new ones (they're kind of a pain to maintain, and we're considering getting rid of them in favor of Pytest fixtures in the future).

2021-07-13 19:19 UTC, wren commented
Oh, also, there seems to be a merge conflict in `tests/test_parse_args.py`. I'm not sure what the conflict is, but you can resolve it if you merge the `develop` branch into your PR.

2021-07-13 19:25 UTC, samuelgregorovic commented
@wren sorry for the misunderstanding. i will take a look

2021-07-17 20:24 UTC, wren commented
@samuelgregorovic No worries!

Also, the develop branch had broken docs tests, which is affecting this PR. If you merge in the develop branch, it should fix that for you. Sorry!

2021-07-31 18:40 UTC, micahellison commented
Hi there @samuelgregorovic, would you like any help with the pytest-bdd tests? If you're not working on them, we can add them in.

2021-08-10 10:47 UTC, samuelgregorovic commented
> Hi there @samuelgregorovic, would you like any help with the pytest-bdd tests? If you're not working on them, we can add them in.

im sorry i was on a holiday and i left it unfinished. i will do it in the following days

2021-08-12 16:23 UTC, wren commented
> > Hi there @samuelgregorovic, would you like any help with the pytest-bdd tests? If you're not working on them, we can add them in.
> 
> im sorry i was on a holiday and i left it unfinished. i will do it in the following days

No worries! This is all volunteer work, and it's always absolutely fine too take your time. Thanks for the response, and please let us know whenever you need any help.

2021-09-06 21:14 UTC, micahellison commented
Hi there @samuelgregorovic -- I started the process of migrating the tests to pytest/bdd and pushed it to this PR, but partway through the process, I found a bug related to the upgrade for older configs. Basically, if you reference the `multiple.yaml` file in the config using `--cf`, it will upgrade it and save over your *main* config file.

If you want to see it in action, backup your jrnl config (or commit it in its own git repo) before running this from the jrnl root:
```
poetry run jrnl --cf tests/data/configs/multiple.yaml this is a test
```

2021-10-09 21:45 UTC, micahellison commented
I fixed that issue with overwriting the default config, then updated the rest of the tests for pytest-bdd. Had to deal with some Python 3.7 issues and a weird timeout with pa11y that somehow resolved after I cleaned up a couple small errors in the documentation. I think this is ready for review now.

2021-10-23 21:45 UTC, micahellison submitted a review, later dismissed

2021-11-06 21:02 UTC, wren commented on tests/lib/given_steps.py
> +    try:
Do we still need this?

2021-11-06 21:11 UTC, wren approved these changes
🎸

2021-11-06 21:12 UTC, merged