Add new, centralized exception handling
jrnl-org/jrnl pull request #1417
Opened 2022-02-19 22:52 UTC by wren

This is the start of fixing #1141 . Once we have centralized exception handling in place (this PR), then we'll be able to go through each error, exception, sys.exit call and get rid of them. There will be a follow-up PR to start going through and remove all of those calls.

### Checklist

- [x] I have read the [contributing doc](https://github.com/jrnl-org/jrnl/blob/develop/CONTRIBUTING.md).
- [x] I have included a link to the relevant issue number.
- [x] I have checked to ensure there aren't other open [pull requests](../pulls)
  for the same issue.
- [x] I have written new tests for these changes, as needed.

2022-02-26 20:47 UTC, micahellison requested changes
Just a couple small comments/questions

2022-02-26 20:47 UTC, micahellison commented on jrnl/editor.py
> +    print_msg(
![image](https://user-images.githubusercontent.com/4383304/155857979-6689f630-d817-45a8-992b-ef415925b227.png)
I think the "To finish writing" instructions should be colorized or at least formatted somehow. What do you think? See screenshot above to illustrate how input text can easily be conflated with the "To finish writing" text.

2022-02-26 20:47 UTC, micahellison commented on jrnl/editor.py
> +        print_msg("Entry NOT saved to journal", msg=Message.NORMAL)
Should this be a "WARNING" instead of "NORMAL"?

2022-02-27 03:09 UTC, wren commented on jrnl/editor.py
> +    print_msg(
Added some brackets around it.

2022-03-12 20:41 UTC, micahellison approved these changes
🎨📝

2022-03-12 20:43 UTC, merged