Update tzlocal to v4.x and remove pytz dependency
jrnl-org/jrnl pull request #1528
Opened 2022-07-03 09:45 UTC by outa

### Changes
- remove `pytz` dependency and replace it with zoneinfo from stdlib (rationale: https://pytz-deprecation-shim.readthedocs.io/en/latest/index.html)
- update tzlocal

### Caveats
There are some differences between pytz's `is_dst` and datetime's `fold` argument: https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html#semantic-differences-between-is-dst-and-fold

I had to adapt a test for this. I don't know what the implications of this would be for jrnl. Please decide if this is reasonable for you.

Closes: #1338

### Checklist

- [X] I have read the [contributing doc](https://github.com/jrnl-org/jrnl/blob/develop/CONTRIBUTING.md).
- [X] I have included a link to the relevant issue number.
- [X] I have checked to ensure there aren't other open [pull requests](../pulls)
  for the same issue.
- [X] I have written new tests for these changes, as needed.

2022-07-09 19:36 UTC, micahellison requested changes
Hi @outa, thank you for working on this! I just merged the develop branch in after our 3.0 release to update the poetry.lock file, and I still see a couple issues in the Mac tests on this PR. Let us know if you have any questions about those or would like any help.

2022-07-14 06:29 UTC, outa commented
Hi Micah! So after you merged the develop branch, the tests were failing on my laptop (using Ubuntu). However in the Gitlab pipeline they passed for some reason. I think we are running into this issue: https://github.com/regebro/tzlocal/issues/131

I am trying to work around that now. However debugging the macOS tests is a bit difficult for me, because I don't have access to a macOS machine. Is there some way to test in a mac environment before pushing changes?

2022-07-16 22:25 UTC, wren submitted a review, later dismissed
This was a tricky one, but you nailed it. Thank you!

2022-07-16 23:00 UTC, micahellison approved these changes, later dismissed

2022-07-30 19:46 UTC, merged