Fix for #1639 journal overwrite
jrnl-org/jrnl pull request #1640
Opened 2022-11-11 22:35 UTC by richardjs

This fixes the journal overwrite bug in #1639. 

There's a bit of awkward branching to account for existing use cases of calling `jrnl --edit` on empty journals; if we drop those, the cleaner fix in fce5afff0632a273de1713bc3a3f6f90c6b7706a could likely work.

### Checklist

- [x] I have read the [contributing doc](https://github.com/jrnl-org/jrnl/blob/develop/CONTRIBUTING.md).
- [x] I have included a link to the relevant issue number.
- [x] I have checked to ensure there aren't other open [pull requests](../pulls)
  for the same issue.
- [x] I have written new tests for these changes, as needed.

2022-11-12 21:19 UTC, micahellison requested changes
Instead of returning, jrnl should open the editor like any other empty search result.

For instance, if you run `jrnl --edit -contain StringThatIsNotInYourJournal` and enter an entry, it will save that new entry.

I'd expect that `jrnl --edit -contain StringThatIsNotInYourJournal --change-time` would behave exactly the same.

2022-11-13 22:33 UTC, richardjs commented
@micahellison, ok, I've modified the fix to behave in that way. I assumed we'd then want to set the newly created entry's time to the value passed to `--change-time` (or the default `now`). Unfortunately, as the change time operation runs before the edit operation ([see here](https://github.com/jrnl-org/jrnl/pull/1452#discussion_r857041184)), I needed to add a little bit of a special case to `_edit_search_results`.

2022-11-19 21:25 UTC, micahellison commented
Thanks @richardjs. @wren and I are chatting about this and realizing that this need for a special case reveals a bigger problem in the original flow that we'd like to fix. We definitely would like to keep your test, but we'll need some more time to think about the rest of it before considering merging this. We'll plan on getting back into this next week.

2023-01-15 00:32 UTC, micahellison commented
Hi again @richardjs, just wanted to let you know, we're still working on this, but it's a bit hairier than we thought. We're basically replacing the branching edit/change-time/delete actions with sequential actions, and I think it will be a lot simpler in the long run, but we're not quite there yet.

2023-03-25 19:30 UTC, micahellison commented
Closing this PR since it's resolved in our larger structural changes in #1669. Thanks for your work on getting this going, @richardjs.

2023-03-25 19:30 UTC, closed without merging