Filter for tagged, untagged and unstarred (#1057)
jrnl-org/jrnl pull request #1663
Opened 2023-01-12 14:25 UTC by cjcon90

This aims to fix jrnl-org/jrnl#1057 - [Filter for entries with no tags](https://github.com/jrnl-org/jrnl/issues/1057)

As discussed in that issue, the preferred syntax is `-not -starred` & `-not -tagged`, as this feels the most intuitive

I aimed to change the existing functionality as little as possible, but making this syntax fit did necessitate some minor changes:
- Add a `-tagged` flag, to show only tagged entries
- Alter `-not` to be allowed to take 0-1 arguments
- Manage parsing in case proceeded by `-starred` or `-tagged`
- If not is not followed by either tag, and is empty, then return the error we would normally get

---

**Note:** While I agree that `-not -starred` etc is the most intuitive syntax (it's what I instinctively tried initially), I'm not crazy about the double usage for the `-not` flag. Ideally each flag should only do one thing, but if we want to go a different route I can take a look at that also :-)

### Checklist

- [X] I have read the [contributing doc](https://github.com/jrnl-org/jrnl/blob/develop/CONTRIBUTING.md).
- [X] I have included a link to the relevant issue number.
- [X] I have checked to ensure there aren't other open [pull requests](../pulls)
  for the same issue.
- [X] I have written new tests for these changes, as needed.

2023-01-14 22:23 UTC, micahellison requested changes
Welcome to jrnl, and thank you for the very complete and thoughtful PR! I like the overall approach you took, and I appreciate the new tests as well.

I just have a couple minor nitpicks around spelling/wording, but I don't think this needs any major changes.

2023-01-14 22:23 UTC, micahellison commented on jrnl/args.py
> +def parse_not_tag(
Could you rename this to `parse_not` or `parse_not_arg`?

2023-01-14 22:23 UTC, micahellison commented on jrnl/args.py
> +    a None value to the exluded list
Just a little typo here - "exluded" instead of "excluded"

2023-01-14 22:36 UTC, cjcon90 commented
@micahellison thank you! Updated both.

Happy to be able to contribute - just started using it daily and really love the app :-)

2023-01-14 22:44 UTC, wren commented
@cjcon90 Hi! We didn't expect you to respond so quickly, and just now merged another PR that will likely cause another merge conflict. Sorry about that!

As soon as that's fixed, we'll get yours merged in. Thanks for the great work!

2023-01-27 21:13 UTC, cjcon90 commented
Sorry meant to do this earlier and completely went out of my head! Rebased my changes so hopefully ready to merge :-)

2023-01-28 19:40 UTC, micahellison approved these changes

2023-01-28 19:41 UTC, micahellison commented
Thanks for the PR and changes! Looks good to me. This still needs to be documented, but I've filled that in a separate issue #1668.

2023-01-28 19:45 UTC, merged